apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson-4
  labels:
    app: lesson-4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lesson-4
  template:
    metadata:
      labels:
        app: lesson-4
    spec:
      containers:
      - name: simple-node
        image: bjoebstl/simple-node
        ports:
        - containerPort: 80
